# Actuarial Valuation in a simple setting
# Yimeng Yin
# 5/22/2015


# This program consists of following files:
  # Model_master.R
  # Model_Decrements.R
  # Model_Salary_Benefit.R
  # Model_IndvLiab.R
  # Model_Population.R
  # Model_AggLiab.R
  # Model_Sim.R
  # Functions.R

# Data:
 # Package "decrements"
 # winklevossdata.rdata:         generated by "Inputs_import_Decrements.R" using "Data/Winklevoss(6).xlsx" and "Data/GAM-1971-Male.xls". 
 # example_Salary_benefit.RData: generated by "Inputs_Salary_Benefit.R" using "Data/PA-PERS.xlsx".  

# Goals: 
# 1. Conduct actuarial valuations each year during a time period of 100 years, allowing for stochastic investment returns.
# 2. Conduct the stochastic simulation in 3 for 10k times. 

# Assumptions
 # Plan Desgin
  # Beneficiary:  : Retirement Only; No disability, death, surivorship benefits
  # Benfit formula: % of FAS per YOS; FAS for last # years
  # Retirment age : NO early retirement
  # Vesting:      : Vested if YOS > #

 # Cost Method
  # 1) EAN(Entry Age Normal)
  # 2) PUC(Projected Unit Credit)

 # Actuarial Assumptions
  # Decrements: Mortality, termination, disability
  # Salary scale
  # Assumed interest rate
  # Inflation
  # Productivity
 
 # Contribution rules: 
    # 1. Sponsor contributes full ADC, which equals the amount of plan cost(Normal cost + supplemental cost) in all periods.
    # 2. Sponsor contributes ADC with a cap, which equals a percentage of total payroll.    
    # 3. Sponsor contributes a fixed percentage of payroll. 

# Outputs
  # Actuarial liability
  # Normal costs
  # Assets
  # UAAL
  # Funded Ratio

# List of tasks:
# Module for reading in model inputs
# Further modulize the model. 
# More options of initial asset value? eg. % of AL




# Preamble ###############################################################################################

rm(list = ls())

library(knitr)
library(data.table)
library(gdata) # read.xls
library(plyr)
library(dplyr)
library(ggplot2)
library(magrittr)
library(tidyr) # gather, spread
library(foreach)
library(doParallel)
library(microbenchmark)
library(data.table)
library(xlsx)
library(XLConnect) # slow but convenient because it reads ranges
#library(corrplot)
# devtools::install_github("donboyd5/decrements")
# devtools::install_github("donboyd5/pp.prototypes")

source("Functions.R")

dev_mode <- TRUE # Enter development mode if true. Parameters and initial population will be imported from Dev_Params.R instead of the RunControl file. 

#*********************************************************************************************************


#*********************************************************************************************************
# 0. Parameters   ####
#*********************************************************************************************************

if(dev_mode) source("Dev_Params.R") else {
  
  # Define Other parameters that depend on the fundamental parameters just imported. 
  paramlist$range_age <- with(Global_paramlist, min.age:max.age)
  
  #paramlist$range.ea  <- c(seq(20, paramlist$r.max, 5), paramlist$r.max) # Assume new entrants only enter the workforce with interval of 5 years. Note that max entry age must be less than max retirement age.  
  #paramlist$range.ea  <- c(20, 25, 30, 35, 45:paramlist$r.max)           # "Continuous" entry ages after 45
  paramlist$range.ea  <- c(20:paramlist$r.max)                           # Complete range of entry ages. Most time comsuming. 
  
  paramlist$v <- with(paramlist, 1/(1 + i))  # discount factor, just for convenience

}

#*********************************************************************************************************
# 1.1 Importing Decrement tables and Calculating Probabilities ####
#*********************************************************************************************************
source("Model_Decrements.R")
# Output: Decrement (data.frame)


#*********************************************************************************************************
# 1.2 Import Salary table and initial retirement benefit table ####
#*********************************************************************************************************

## Inputs
 # Data frames:
 #  - data frame for initial actives
 #  - data frame for initial retirees
 #  - data frame for salary  scale
 # Parameters:
 #  - planname: plan to be selected from the data frames above. From the RunControl file
 #  - paramList

# Notes:
# 1. User must provide the following data frames
#   "salary":  a complete salary table containing salary history of current actives and projected salary path for future workers,
#              both of which are calculated based on a salary table of current actives from the AV and assumptions on salary growth.  
#   "benefit": a data frame containing average retirement benefit payment(including both service retirement and deferred retirement)
#              of all valid ea and age combos. The user MUST make sure the smallest age in the retirement benefit table is smaller than the 
#              single retirement age specified in parameter section. (smaller than r.min with multiple retirement ages)
# 2. Note that avgben is only used to calculate the current and projected values of benefits and liabilities of retirees at year 1. Future retirees' 
#    benefits and liabilities are calculated based on their salary history provided in "salary". 
# 3. I don't think in "avgben" we need average benefit for all combos of ea and age. All we need is actually average benefits
#    by age. Once we have that we can assign an arbitrary ea to it an throw it into the model. Note that the AV of NJ-TPAF only contains 
#    average benefits for retirees and vested terms by age group. Also note that if service retirees and vested terms follow the same mortality table 
#    and have the same COLA rule, I don't think we need to distinguish between them.     
#

# Artificial salary table and benefit table for testing purpose are imported by sourcing the following script.
# These tables are based on PA-PSERS and some naive assumptions for imputation.
# Please do NOT source the script below if external salary and benefit tables are used.   
# source("Inputs_Salary_Benefit.R")
source("Model_Salary_Benefit.R")


#*********************************************************************************************************
# 1.3  Actual investment return. ####
#*********************************************************************************************************

if(dev_mode){
set.seed(1234)
#i.r <- with(Global_paramlist, matrix(rnorm(nyear*nsim, mean = 0.08, sd = 0.12),nrow = nyear, ncol = nsim)) 
i.r <- with(Global_paramlist, matrix(0.08, nrow = nyear, ncol = nsim))
i.r[10,] <- 0.00 # Create a loss due to zero return in year 10. For the purpose of checking amortization of UAAL

} else {
  i.r <- with(Global_paramlist, matrix(rnorm(nyear*nsim, mean = ir.mean, sd = ir.sd),nrow = nyear, ncol = nsim))
}



#*********************************************************************************************************
# 2. Individual actuarial liabilities, normal costs and benenfits ####
#*********************************************************************************************************
source("Model_IndivLiab.R")



#*********************************************************************************************************
# 3. Workforce ####
#*********************************************************************************************************
# Simulation of the workforce is done in the file below: 
source("Model_Population.R")



#*********************************************************************************************************
# 4. Aggregate actuarial liabilities, normal costs and benenfits ####
#*********************************************************************************************************
source("Model_AggLiab.R")


#*********************************************************************************************************
# 5.  Simulation ####
#*********************************************************************************************************
source("Model_Sim.R")


#*********************************************************************************************************
# 6. Results ####
#*********************************************************************************************************

options(digits = 2, scipen = 6)

# select variables to be displayed in the kable function. See below for a list of all avaiable variables and explanations.
var.display <- c("year",  "AL",    "MA",    "AA",   "FR",  
                 # "ExF",   
                 "UAAL",  "EUAAL", "LG",    "NC",    "SC",    
                 "ADC", "EEC", "ERC",  "C", "B"     
                 # "I.r" ,   "I.e",  "i",    "i.r"
                 # "PR", "ADC_PR", "C_PR"
                 # "AM"
                 # "C_ADC"
                 )

r1 <- penSim_results[[1]][,var.display]
kable(r1, digits = 2)


# # Conbine results into a data frame. 
# df <- bind_rows(penSim_results) %>% 
#       mutate(sim=rep(1:nsim, each=nyear)) %>%
#       select(sim, year, everything())

# Running time of major modules
Time_liab # liability
Time_wf   # workforce
Time_prep_loop # Preparing for the loop
Time_loop # the big loop


(Time_liab + Time_wf + Time_prep_loop + Time_loop)[3]/60 # # of minutes


# AL: Total Actuarial liability, which includes liabilities for active workers and pensioners.
# NC: Normal Cost  
# MA: Market value of assets.
# AA: Actuarial value of assets.
# EAA:Expected actuarial value of assets.(used with asset smoothing method in TPAF)
# UAAL: Unfunded accrued actuarial liability, defined as AL - NC
# EUAAL:Expected UAAL.
# PR: payroll 
# LG: Loss/Gain, total loss(positive) or gain(negative), Caculated as LG(t+1) = (UAAL(t) + NC(t))(1+i) - C - Ic - UAAL(t+1), 
# AM: Amount to be amortized at period t, it is the sum of loss/gain and shortfall in ADC payment. 
# i is assumed interest rate. AMs of each period will be amortized seperately.  
# SC: Supplement cost 
# ADC: ADC
# C : Actual contribution
# C_ADC: shortfall in paying ADC (C - ADC). Note that negative number means shortall. 
# B : Total benefit payment(currently all to retirees)   
# Ic: Assumed interest from contribution, equal to i*C if C is made at the beginning of time period. i.r is real rate of return. 
# Ia: Assumed interest from AA, equal to i*AA if the entire asset is investible. 
# Ib: Assumed interest loss due to benefit payment, equal to i*B if the payment is made at the beginning of period
# I.r : Total ACTUAL interet gain, I = i.r*(AA + C - B), if AA is all investible, C and B are made at the beginning of period.
# Funded Ratio: AA / AL
# C_PR: contribution as % of payroll





