# Actuarial Valuation in a simple setting
# Yimeng Yin
# 5/27/2015


# This program consists of following files:
  # Model_master.R
  # Model_Decrements.R
  # Model_Import_Plan.R
  # Model_InvReturns.R
  # Model_Population.R
  # Model_IndvLiab.R
  # Model_AggLiab.R
  # Model_Sim.R
  # Functions.R

# Data:
 # Package "pp.prototypes" 
 # Package "decrements"
 # winklevossdata.rdata:         generated by "Inputs_import_Decrements.R" using "Data/Winklevoss(6).xlsx" and "Data/GAM-1971-Male.xls". 
 # example_Salary_benefit.RData: generated by "Inputs_Salary_Benefit.R" using "Data/PA-PERS.xlsx". ((no longer used in curretn version) 

# Goals: 
# 1. Conduct actuarial valuations each year during a time period of 100 years, allowing for stochastic investment returns.
# 2. Conduct the stochastic simulation for 2000 times. 

# Assumptions
 # Plan Desgin
  # Beneficiary:  : Retirement Only; No disability, death, surivorship benefits
  # Benfit formula: % of FAS per YOS; FAS for last # years
  # Retirment age : NO early retirement
  # Vesting:      : Vested if YOS > #

 # Cost Method
  # 1) EAN(Entry Age Normal)
  # 2) PUC(Projected Unit Credit)

 # Actuarial Assumptions
  # Decrements: Mortality, termination, disability
  # Salary scale
  # Assumed interest rate
  # Inflation
  # Productivity
 
 # Contribution rules: 
    # 1. Sponsor contributes full ADC, which equals the amount of plan cost(Normal cost + supplemental cost) in all periods.
    # 2. Sponsor contributes ADC with a cap, which equals a percentage of total payroll.    
    # 3. Sponsor contributes a fixed percentage of payroll. 

# Outputs
  # Actuarial liability
  # Normal costs
  # Assets
  # UAAL
  # Funded Ratio

## List of tasks:
 # How to deal with negative asset values and contributions
 # How to set parameter g in constant percent amortization method. Now infl + prod



print(paramlist$runname)

#*********************************************************************************************************
# 0. Parameters (deprecated)  ####
#*********************************************************************************************************

if(devMode) source("Dev_Params.R") else {
  
  # Define Other parameters that depend on the fundamental parameters just imported. 
  paramlist$range_age <- with(Global_paramlist, min.age:max.age)
  paramlist$range_ea  <- c(Global_paramlist$min.age:(paramlist$r.max - 1))
  
  paramlist$v <- with(paramlist, 1/(1 + i))  # discount factor, just for convenience
  
}

#*********************************************************************************************************
# 1.1 Importing Decrement tables and Calculating Probabilities ####
#*********************************************************************************************************
source("Model_Decrements.R")
# Output: Decrement (data.frame)


#*********************************************************************************************************
# 1.2 Import Salary table and initial retirement benefit table ####
#*********************************************************************************************************

## Inputs
 # Data frames:
 #  - data frame for initial actives
 #  - data frame for initial retirees
 #  - data frame for salary  scale
 # Parameters:
 #  - planname: plan to be selected from the data frames above. From the RunControl file
 #  - paramList

# Notes:
# 1. User must provide the following data frames
#   "salary":  a complete salary table containing salary history of current actives and projected salary path for future workers,
#              both of which are calculated based on a salary table of current actives from the AV and assumptions on salary growth.  
#   "benefit": a data frame containing average retirement benefit payment(including both service retirement and deferred retirement)
#              of all valid ea and age combos. 
# 2. Note that avgben is only used to calculate the current and projected values of benefits and liabilities of retirees at year 1. Future retirees' 
#    benefits and liabilities are calculated based on their salary history provided in "salary". 
# 3. I don't think in "avgben" we need average benefit for all combos of ea and age. All we need is actually average benefits
#    by age. Once we have that we can assign an arbitrary ea to it an throw it into the model. Note that the AV of NJ-TPAF only contains 
#    average benefits for retirees and vested terms by age group. Also note that if service retirees and vested terms follow the same mortality table 
#    and have the same COLA rule, I don't think we need to distinguish between them.     


source("Model_Import_Plan.R")


#*********************************************************************************************************
# 1.3  Actual investment return. ####
#*********************************************************************************************************
source("Model_InvReturns.R")


#*********************************************************************************************************
# 2. Population ####
#*********************************************************************************************************
source("Model_Population.R")
gc()


#*********************************************************************************************************
# 3. Individual actuarial liabilities, normal costs and benenfits ####
#*********************************************************************************************************
source("Model_IndivLiab.R")
gc()


#*********************************************************************************************************
# 4. Aggregate actuarial liabilities, normal costs and benenfits ####
#*********************************************************************************************************
source("Model_AggLiab.R")
gc()

#*********************************************************************************************************
# 5.  Simulation ####
#*********************************************************************************************************
source("Model_Sim.R")


#*********************************************************************************************************
# 6. Results ####
#*********************************************************************************************************

options(digits = 4, scipen = 6)

# select variables to be displayed in the kable function. See below for a list of all avaiable variables and explanations.
var.display <- c("year",  "AL",    "AA",   "FR", "NC",    "SC", "UAAL", "PVFB.act",
                 "AL.act_PR", "AL.ret_PR", "AL.Ben_PR",
                 "NC.act_PR",
                 #"AL_PR", "NC_PR", "SC_PR", "C_PR", "ERC_PR", 
                 # "PR", "PR.growth", 
                 # "ExF",   
                 # "UAAL",  "EUAAL", "LG",    "NC",    "SC",    
                 #"ADC", "EEC", "ERC",  
                 "C", "B",
                 "AL_PVFB", 
                 "NC_PVFB",
                 "PR_PVFB",
                 "NC_growth",
                 "AL_growth",
                 "PR_growth",
                 "PV_growth",
                 "B_growth"
                 
                 
                 # "I.r" ,   "I.e"
                 # "i",    "i.r"
                 #, "dERC_PR"
                 # "AM", "PR",
                 # "C_ADC"
)

r1 <- penSim_results %>% mutate(B.v_B = B.v / B * 100,
                                AL_PVFB = AL.act / PVFB.act,
                                NC_PVFB = NC.act / PVFB.act,
                                PR_PVFB = PR / PVFB.act,
                                NC_growth = NC/lag(NC) - 1,
                                AL_growth = AL/lag(AL) - 1,
                                PR_growth = PR/lag(PR) - 1,
                                PV_growth = PVFB.act/lag(PVFB.act) - 1,
                                B_growth  = B / lag(B) - 1) %>% 
  
  
filter(sim == -1, year %in% 90:105) %>% select(one_of(var.display))
kable(r1, digits = 3)





# Running time of major modules
Time_liab # liability
Time_wf   # workforce
Time_prep_loop # Preparing for the loop
Time_loop # the big loop


(Time_liab + Time_wf + Time_prep_loop + Time_loop)[3]/60 # # of minutes


# AL: Total Actuarial liability, which includes liabilities for active workers and pensioners.
# NC: Normal Cost  
# MA: Market value of assets.
# AA: Actuarial value of assets.
# EAA:Expected actuarial value of assets.(used with asset smoothing method in TPAF)
# UAAL: Unfunded accrued actuarial liability, defined as AL - NC
# EUAAL:Expected UAAL.
# PR: payroll 
# LG: Loss/Gain, total loss(positive) or gain(negative), Caculated as LG(t+1) = (UAAL(t) + NC(t))(1+i) - C - Ic - UAAL(t+1), 
# AM: Amount to be amortized at period t, it is the sum of loss/gain and shortfall in ADC payment. 
# i is assumed interest rate. AMs of each period will be amortized seperately.  
# SC: Supplement cost 
# ADC: ADC
# C : Actual contribution
# C_ADC: shortfall in paying ADC (C - ADC). Note that negative number means shortall. 
# B : Total benefit payment(currently all to retirees)   
# Ic: Assumed interest from contribution, equal to i*C if C is made at the beginning of time period. i.r is real rate of return. 
# Ia: Assumed interest from AA, equal to i*AA if the entire asset is investible. 
# Ib: Assumed interest loss due to benefit payment, equal to i*B if the payment is made at the beginning of period
# I.r : Total ACTUAL interet gain, I = i.r*(AA + C - B), if AA is all investible, C and B are made at the beginning of period.
# Funded Ratio: AA / AL
# C_PR: contribution as % of payroll


#*********************************************************************************************************
# 6. Writing outputs ####
#*********************************************************************************************************


outputs_list <- list(paramlist = paramlist, 
                     Global_paramlist = Global_paramlist,
  
                     decrement = decrement,
                     
                     results     = penSim_results,
                     
                     ind_active  = AggLiab$ind_active, 
                     ind_retiree = AggLiab$ind_retiree,
                     ind_term    = AggLiab$ind_term,
                     demo_summary= pop$demo_summary,
                     
                     #liab  = if(paramlist$save.liab) liab else "Not saved",
                     #demo  = if(paramlist$save.demo) pop else "Not saved",
                     
                     entrant_dist = entrants_dist)

# Save outputs to specified folder
if(!file.exists(folder_run)) dir.create(folder_run)

# filename_outputs <- paste0("Outputs_",  paramlist$runname, "_" , format(Sys.Date(), "%m-%d-%Y"), ".RData")
filename_outputs <- paste0("Outputs_",  paramlist$runname, ".RData")

# save(outputs_list, file = paste0(folder_run,"/", filename_outputs))

gc()
outputs_list$results

outputs_list$results

# #*********************************************************************************************************
# # Examining steady state ####
# #*********************************************************************************************************
# 
# # 1. Active members
# 
# left_join(
# pop$active %>% 
#   filter(year  ==  99, ea ==20, age <=60) %>% rename(number.a1 = number.a), 
# 
# pop$active %>% 
#   filter(year  ==  100, ea ==20, age <=60) %>% rename(number.a2 = number.a),
# by = c("ea", "age")
# ) %>% 
# select(year.x, year.y,everything()) %>% 
# mutate(diff = number.a2 / number.a1 - 1)
# 
# 
# # 2. Retirees 
# 
# df_ret <- pop$retired %>% 
#   group_by(year, age) %>% 
#   summarize(number.r = sum(number.r))
# 
# left_join(
#   df_ret %>% 
#     filter(year  ==  99, age >60) %>% rename(number.r1 = number.r), 
#   
#   df_ret %>% 
#     filter(year  ==  100, age >60) %>% rename(number.r2 = number.r),
#   by = c("age")
# ) %>% 
#   ungroup %>% 
#   select(year.x, year.y,everything()) %>% 
#   mutate(diff = number.r2 / number.r1 - 1) %>% as.data.frame()
# 
# # The demographics have become quite stable after 100 years. Annual changes in any cell generally smaller than 0.01%
# # Year 100 value should be ok to be used as a steady state.
# 
# 
# 
# # 3. Verify the stability of NC/PVB, AL/PVB, PR/PVB, and growth of liability
# 
# df_actives <- left_join(pop$active, liab$active) # %>% left_join(new_retirees)
# df_actives[-(1:3)] <- colwise(na2zero)(df_actives[-(1:3)]) # replace NAs with 0, so summation involing missing values will not produce NAs. 
# 
# 
# df_actives %>% head
# 
# df_actives %<>% 
#   mutate(NC_PR  = NCx / sx,
#          AL_PR  = ALx / sx,
#          PVB_PR = PVFBx.r / sx)
# 
# df_actives %>% 
#   filter(ea == 20, age == 55)
# 
# 
# 
# 
# #*********************************************************************************************************
# # Saving steady state ####
# #*********************************************************************************************************
# 
# # actives
# df_actives <- left_join(pop$active, liab$active) # %>% left_join(new_retirees)
# df_actives[-(1:3)] <- colwise(na2zero)(df_actives[-(1:3)]) # replace NAs with 0, so summation involing missing values will not produce NAs. 
# 
# 
# ss_actives  <- 
#   df_actives %>% 
#   select(-ALx.v, -PVFBx.v, -NCx.v) %>% 
#   filter(year == 100, age < 60) %>% 
#   mutate(NC_PVB = NCx / PVFBx.r,
#          AL_PVB = ALx / PVFBx.r) %>% 
#   arrange(ea, age)
# ss_actives %>% head
# 
# # retirees
# 
# df_retiree <- 
# merge(
# data.table(liab$retiree, key = "ea,age,year,year.retire"),
# data.table(pop$retired,  key = "ea,age,year,year.retire"),
# by = c("ea", "age","year", "year.retire"), all.x = TRUE) %>% 
#   as.data.frame()
# 
# ss_retirees <- 
#   df_retiree %>% 
#   ungroup() %>% 
#   filter(year == 100, age >= 60, number.r != 0) %>% 
#   arrange(age, ea)
# 
# 
# ss_retirees %>% group_by(age) %>% 
#   summarize(number.ret = sum(number.r),
#             B.r      = sum(number.r * B.r),
#             AL.r     = sum(number.r * ALx.r)) %>% 
#   as.data.frame
# 
# save(ss_decrement = decrement,
#      ss_actives,
#      ss_retirees,
#      file = "SteadyState/SteadyState2.RData")
# 
# 



#*******************************************************************************
# Saving demographics ####
#*******************************************************************************

# actives
df_actives <- left_join(pop$active, liab$active, by = c("year", "ea", "age")) 
df_actives[-(1:3)] <- colwise(na2zero)(df_actives[-(1:3)]) # replace NAs with 0, so summation involing missing values will not produce NAs.
df_actives %<>%
  #select(ALx.v, PVFBx.v, NCx.v) %>%
  rename(ALx.r = ALx,
         NCx.r = NCx) %>% 
  filter(age < 60) %>%
  # mutate(NC_PVB = NCx / PVFBx.r,
  #        AL_PVB = ALx / PVFBx.r) %>%
  arrange(year, ea, age) %>% 
  ungroup() %>% 
  as_tibble()

df_actives %>% head


# retirees
df_retirees <-
   merge( # Faster than left_join
     data.table(liab$retiree, key = "ea,age,year,year.retire"),
     data.table(pop$retired,  key = "ea,age,year,year.retire"),
     by = c("ea", "age","year", "year.retire"), all.x = TRUE) %>%
     as_tibble()

df_retirees <-
  df_retirees %>%
  ungroup() %>%
  filter(age >= 60) %>%
  arrange(age, ea)

df_retirees

# terminated

df_terms <-
  merge( # Faster than left_join
    data.table(liab$term, key = "ea,age,year,year.term"),
    data.table(pop$term,  key = "ea,age,year,year.term"),
    by = c("ea", "age","year", "year.term"), all.x = TRUE) %>%
  as_tibble()

df_terms <-
  df_terms %>%
  ungroup() %>%
  filter(age >= 20) %>%
  arrange(age, ea)

df_terms




liab$term
pop$term


save(decrement,
     df_actives,
     df_retirees,
     df_terms,
     file = paste0("Inputs_riskSharing/", runName, ".RData"))


save(decrement,
     df_actives,
     df_retirees,
     df_terms,
     file = paste0("C:/Git/PenSim_riskSharing/Inputs/", runName, ".RData"))


# 
outputs_list$results %>%
  select(runname, sim, year, NC_PR,NC.term_PR, FR_MA, AL.act, AL.term, AL.ret, AL.Ben, B, B.v, PR, PVFB.act, PVFB.v) %>%
  mutate(B.v_share = B.v / B,
         PVFB.v_share = PVFB.v / PVFB.act,
         AL_termed = AL.Ben -  AL.ret) 














