---
title: "Exploratory Analysis of Model Outputs"
author: "Yimeng Yin"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 4
---


```{r mainSet options, echo=FALSE, cache=FALSE}

# options(width=120)
# knitr::opts_chunk$set(fig.width=14, fig.height=5, echo=FALSE)
# # Note: when saving maps (ggsave), width=16, height=9 seems to get rid of white space

```




```{r Preamble, echo = FALSE, include  = FALSE}
library(reshape2)
library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(knitr)
library(magrittr) # to use %<>%

rm(list = ls())

run_knitr <- T

if(run_knitr) source("../Functions.R") else source("Functions.R")


```


```{r Read, echo=FALSE, include = FALSE}
## Combine selected files into a single list.

if(run_knitr) folder_run <- "../IO_ActMethods" else folder_run <- "IO_ActMethods"

file_select <- dir(folder_run, pattern = ".RData")

fn <- function(x) {
       load(paste0(folder_run, "/", x))
       outputs_list
  }

lists_all        <- alply(file_select, 1, fn)
names(lists_all) <- laply(lists_all, function(x) x$paramlist$runname)

## Combine the results into a single data frame.
results_all <- ldply(lists_all, function(x) x$results) %>% select(-X1)


```



```{r, include = FALSE, eval= FALSE}

# select variables to be displayed in the kable function. See below for a list of all avaiable variables and explanations.
var.display <- c("runname", "year",  "AL",    "MA",    "AA",   "FR", # "FR_MA",
                 # "ExF",   
                 # "UAAL",  "EUAAL", "LG",    
                 "NC",    "SC", "ADC", "EEC", "ERC",  "C", "B",     
                 # "I.r" ,   "I.e", 
                 # "i",    "i.r",
                 "ADC_PR", "C_PR", "ERC_PR", "PR"# , "dERC_PR"
                 # "AM", "PR",
                 # "C_ADC"
                 )

r1 <- results_all %>% filter(sim %in% 1, year == 1) %>% select(one_of(var.display)) 
kable(r1, digits = 2)



```



# ADC rate(also NC rate)

```{r, echo = FALSE, cache = F , eval = TRUE}

results_all %>% select(runname, year, ADC_PR) %>% filter(runname %in% paste0(c("EAN_", "PUC_"),"Avg")) %>% 
  ggplot(aes(year, ADC_PR, color = runname)) + geom_line() + geom_point() + coord_cartesian(ylim = c(3,11))

results_all %>% select(runname, year, ADC_PR) %>% filter(runname %in% paste0(c("EAN_", "PUC_"),"Unif")) %>% 
  ggplot(aes(year, ADC_PR, color = runname)) + geom_line() + geom_point() + coord_cartesian(ylim = c(3,11))

results_all %>% select(runname, year, ADC_PR) %>% filter(runname %in% paste0(c("EAN_", "PUC_"),"mc")) %>% 
  ggplot(aes(year, ADC_PR, color = runname)) + geom_line() + geom_point() + coord_cartesian(ylim = c(3,11))

```


# Difference in ADC rate

The difference is not that big. 
But average distribution does gives the highest difference between PUC and EAN in NC rate,
while Matkin/Chen gives the lowest. 

```{r, echo = FALSE, cache = F , eval = TRUE}

results_all %>% select(runname, year, ADC_PR) %>% spread(runname, ADC_PR) %>% 
  mutate(Diff_Avg  = PUC_Avg - EAN_Avg,
         Diff_Unif = PUC_Unif - EAN_Unif,
         Diff_mc   = PUC_mc -EAN_mc) %>% 
  select(year, starts_with("Diff")) %>% 
  gather(PopDist, Diff, -year) %>% 
  ggplot(aes(year, Diff, color = PopDist)) + geom_line() + geom_point() + coord_cartesian(ylim = c(0,3))
```


# %Difference in ADC (also in ADC rate)

```{r, echo = FALSE}
results_all %>% select(runname, year, ADC_PR) %>% spread(runname, ADC_PR) %>% 
  mutate(DiffPct_Avg  = 100*(PUC_Avg - EAN_Avg)/EAN_Avg ,
         DiffPct_Unif = 100*(PUC_Unif - EAN_Unif)/EAN_Unif,
         DiffPct_mc   = 100*(PUC_mc - EAN_mc)/EAN_mc) %>% 
  select(year, starts_with("Diff")) %>% 
  gather(PopDist, DiffPct, -year) %>% 
  ggplot(aes(year, DiffPct, color = PopDist)) + geom_line() + geom_point() + coord_cartesian(ylim = c(0,80))

```





