---
title: "Exploratory Analysis of Model Outputs"
author: "Yimeng Yin"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 4
---


```{r mainSet_options, echo=FALSE, cache=FALSE}

# options(width=140)
# knitr::opts_chunk$set(fig.width=16, fig.height=5, echo=FALSE)
# # Note: when saving maps (ggsave), width=16, height=9 seems to get rid of white space

```



```{r Preamble, echo = FALSE, include  = FALSE}
library(reshape2)
library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(knitr)
library(magrittr) # to use %<>%
library(zoo)
library(grid)
library(gridExtra)
library(stringr)

rm(list = ls())

run_knitr <- F  #set to TRUE before knitting.
# When knitting HTML files, the working directory will be changed to the on where the .rmd file is located.
# The relative paths must be modified if they are not relative to the folder the .rmd file is located. 
# (When running the code line by line, it is covenient to set the paths relative to the folder of main model.)
  

if(run_knitr) source("../Functions.R") else source("Functions.R")
```


```{r Read, echo=FALSE, include = FALSE}
## Combine selected files into a single list.

IO_folder <- "IO_M1_new"

if(run_knitr) IO_folder <- paste0("../", IO_folder)

get_results <- function(IO_folder){
  
  fn <- function(x) {
    load(paste0(IO_folder, "/", x))
    outputs_list$results}

  file_select <- dir(IO_folder, pattern = "^Outputs")
  results_all <- adply(file_select, 1, fn) %>% select(-X1)
}

results_all <- get_results(IO_folder)
```


```{r, echo=FALSE, include = FALSE}

var.display <- c( "runname", "year",
                 "FR","AL","AA",
                 #"AL_PR", "AL.act_PR", "AL.ret_PR","AL.term_PR", 
                 "NC_PR", "NC.act_PR", "NC.term_PR", 
                 "SC_PR", "C_PR", "ERC_PR",
                 "MA_PR",   
                 "PR.growth", 
                 "ExF_PR",
                 "AL", "C","B","PR",
                 "ExF",
                 "i.r"
)

results_all %>% filter(runname =="A1F100_O30pA5", sim == 0) %>% select(one_of(var.display))

```



# Funding policies: Figure 11 in M1 report

```{r, echo = FALSE, cache = F , eval = TRUE, fig.width=20, fig.height=4}

prefix <- "A1F075_"
runs_M1_F11 <- c(
 "0",
 "O15d",
 "O15p",
 "O30d",
 "O30p",
 "C30p",
 "O30pA5"
)

draw_quantiles(c(paste0(prefix, runs_M1_F11)), "FR_MA",  ylim = c(0, 250),  year.max = 60)$plot %>% print
draw_quantiles(c(paste0(prefix, runs_M1_F11)), "C_PR",   ylim = c(-2, 35),  year.max = 60)$plot %>% print
#draw_quantiles(c(paste0(prefix, runs_M1_F11)), "ERC_PR", ylim = c(-2, 35),  year.max = 60)$plot %>% print
draw_quantiles(c(paste0(prefix, runs_M1_F11)), "MA_PR",  year.max = 60)$plot %>% print
```




# Funding policies: SOA/BRP runs
```{r, echo = FALSE, cache = F , eval = TRUE, fig.width=20, fig.height=4}
prefix <- "A1F075_"
runs_M1_soa <- c(
  "O30pA5",
  "soa1", "soa2", "soa3", "soa4"
)

draw_quantiles(c(paste0(prefix, runs_M1_soa)), "FR_MA", ylim = c(0, 250), year.max = 60)$plot %>% print
draw_quantiles(c(paste0(prefix, runs_M1_soa)), "C_PR",  ylim = c(-2, 50),  year.max = 60)$plot %>% print
#draw_quantiles(c(paste0(prefix, runs_M1_soa)), "ERC_PR",ylim = c(-2, 50),year.max = 60)$plot %>% print
draw_quantiles(c(paste0(prefix, runs_M1_soa)), "MA_PR",year.max = 60)$plot %>% print

```



# Funding policies: Runs with ERC_PR cap
```{r, echo = FALSE, cache = F , eval = TRUE, fig.width=20, fig.height=4}
prefix <- "A1F075_"
runs_M1_cap <- c("O30pA5", "O30pA5_cap", "soa1", "soa1_cap", "soa3", "soa3_cap")

draw_quantiles(c(paste0(prefix, runs_M1_cap)), "FR_MA", ylim = c(0, 250), year.max = 60)$plot %>% print
draw_quantiles(c(paste0(prefix, runs_M1_cap)), "C_PR",  ylim = c(-2, 35),  year.max = 60)$plot %>% print
#draw_quantiles(c(paste0(prefix, runs_M1_cap)), "ERC_PR",ylim = c(-2, 35),year.max = 60)$plot %>% print
draw_quantiles(c(paste0(prefix, runs_M1_cap)), "MA_PR", year.max = 60)$plot %>% print

```


```{r, eval=FALSE, fig.height=4, fig.width=20, cache=F, include=FALSE}

prefix <- "A1F075_"

runs_M1_O <- c(
# "0",  
 "O15d",
 "O15p",
 "O30d",
 "O30p",  
 "O30pA5",
 "O30pA10"
)

runs_M1_C <- c(
 # "0",  
 "C15d",
 "C15p",
 "C30d",
 "C30p",  
 "C30pA5",
 "C30pA10"
)

runs_M1_0 <- c( "0u","0","A5","A10")


draw_quantiles(c(paste0(prefix, runs_M1_O)), "FR_MA",  ylim = c(0, 250), year.max = 60)$plot %>% print
draw_quantiles(c(paste0(prefix, runs_M1_O)), "C_PR",   ylim = c(-2, 35),  year.max = 60)$plot %>% print
draw_quantiles(c(paste0(prefix, runs_M1_O)), "ERC_PR", ylim = c(-2, 35),year.max = 60)$plot %>% print
draw_quantiles(c(paste0(prefix, runs_M1_O)), "MA_PR",  year.max = 60)$plot %>% print


draw_quantiles(c(paste0(prefix, runs_M1_C)), "FR_MA", ylim = c(0, 250), year.max = 60)$plot %>% print
draw_quantiles(c(paste0(prefix, runs_M1_C)), "C_PR",  ylim = c(-2, 35),  year.max = 60)$plot %>% print
draw_quantiles(c(paste0(prefix, runs_M1_C)), "ERC_PR",ylim = c(-2, 35),year.max = 60)$plot %>% print
draw_quantiles(c(paste0(prefix, runs_M1_C)), "MA_PR", year.max = 60)$plot %>% print
 

draw_quantiles(c(paste0(prefix, runs_M1_0)), "FR_MA", ylim = c(0, 250), year.max = 60)$plot %>% print
draw_quantiles(c(paste0(prefix, runs_M1_0)), "C_PR",  ylim = c(-2, 35),  year.max = 60)$plot %>% print
draw_quantiles(c(paste0(prefix, runs_M1_0)), "ERC_PR",ylim = c(-2, 35),year.max = 60)$plot %>% print
draw_quantiles(c(paste0(prefix, runs_M1_0)), "MA_PR", year.max = 60)$plot %>% print


# "A1F100_O30pA5",
draw_quantiles(c("A1F075_O30pA5", "A1F100_O30pA5"), "FR_MA", ylim = c(0, 250), year.max = 60)$plot %>% print
draw_quantiles(c("A1F075_O30pA5", "A1F100_O30pA5"), "C_PR", ylim = c(-2, 35),  year.max = 60)$plot %>% print
#draw_quantiles(c("A1F075_O30pA5", "A1F100_O30pA5"), "ERC_PR", ylim = c(-2, 35),year.max = 60)$plot %>% print
draw_quantiles(c("A1F075_O30pA5", "A1F100_O30pA5"), "MA_PR",year.max = 60)$plot %>% print

```


# -25% asset shock

```{r, echo = FALSE, cache = F , eval = TRUE, fig.width=20, fig.height=10}


prefix <- "A1F075_"

runs_M1_shock <- c(
"0_a",
"O30p_a",
"O30pA5_a",
"O30pA10_a"
)

draw_quantiles(c(paste0(prefix, runs_M1_shock)), "FR",     ylim = c(0, 250), year.max = 20)$plot %>% print
draw_quantiles(c(paste0(prefix, runs_M1_shock)), "C_PR",   ylim = c(-2, 35),  year.max = 20)$plot %>% print
#draw_quantiles(c(paste0(prefix, runs_M1_shock)), "ERC_PR", ylim = c(-2, 35),year.max = 20)$plot %>% print
draw_quantiles(c(paste0(prefix, runs_M1_shock)), "MA_PR",  year.max = 20)$plot %>% print


```


# Geo vs arith mean

0: ir.mean = 7.5; 1: ir.mean = 8.22


```{r, echo = FALSE, cache = F , eval = TRUE, fig.width=20, fig.height=10}

prefix <- "B1F075_"

runs_M1_GvA <- c(0, 1)

draw_quantiles(c(paste0(prefix, runs_M1_GvA)), "FR_MA", ylim = c(0, 250),  year.max = 60)$plot %>% print
draw_quantiles(c(paste0(prefix, runs_M1_GvA)), "C_PR",  ylim = c(-2, 35),  year.max = 60)$plot %>% print
# draw_quantiles(c(paste0(prefix, runs_M1_GvA)), "ERC_PR", ylim = c(-2, 35), year.max = 60)$plot %>% print
draw_quantiles(c(paste0(prefix, runs_M1_GvA)), "MA_PR", year.max = 60)$plot %>% print

```




```{r measures, eval = FALSE, echo = FALSE}

# Metrics of risks and volatility 

# Measures:
# 1. standard deviation over first 30 years, for a typical simulation
# 2. largest bad-direction change in any 5-year interval of first 30 years - typical simulation
# 3. Worst value in ANY of first 30 years - typical simulation
# 4. Value at the end of 30 years - typical simulation 

df_sd <- results_all %>% filter(year <= 30, sim >=1) %>% 
                select(runname, year, sim, FR_MA, C_PR, ERC_PR, MA_PR) %>% 
                group_by(sim, runname) %>% 
                summarise_each(funs(sd(., na.rm = TRUE)), one_of(c("FR_MA", "C_PR", "ERC_PR", "MA_PR"))) %>% 
                group_by(runname) %>% 
                summarise_each(funs(median)) %>% select(-sim)


df_worst <- results_all %>% filter(year <= 30, sim >=1) %>% 
                select(runname, year, sim, FR_MA, C_PR, ERC_PR, MA_PR) %>% 
                group_by(sim, runname) %>% 
                summarise(FR_MA = min(FR_MA), C_PR = max(C_PR), ERC_PR = max(ERC_PR), MA_PR = min(MA_PR)) %>% 
                group_by(runname) %>% 
                summarise_each(funs(median)) %>% select(-sim)



df_final <- results_all %>% filter(year <= 30, sim >=1) %>% 
                select(runname, year, sim, FR_MA, C_PR, ERC_PR, MA_PR) %>% 
                group_by(sim, runname)    %>% 
                filter(year == max(year)) %>% 
                group_by(runname) %>% 
                summarise_each(funs(median)) %>% select(-sim)



df_5yearChg <- results_all %>% filter(year <= 30, sim >=1) %>% 
                select(runname, year, sim, FR_MA, C_PR, ERC_PR, MA_PR) %>% 
                group_by(sim, runname)  %>% 
                mutate_each(funs(. - lag(., 5)), one_of(c("FR_MA", "C_PR", "ERC_PR", "MA_PR")) ) %>% 
                summarise(FR_MA = min(FR_MA,  na.rm = TRUE),
                          C_PR  = max(C_PR,   na.rm = TRUE),
                          ERC_PR= max(ERC_PR, na.rm = TRUE),
                          MA_PR = min(MA_PR,  na.rm = TRUE)) %>% 
                group_by(runname) %>% 
                summarise_each(funs(median)) %>% select(-sim)


## Create functions to calculate max changes in 5-year intervals. 

maxChgWithin <- function(y, fn, ...){
   # max/min change within a single interval.
   zoo::rollapply(y, rev(seq_along(y)), function(x) fn(x - x[1], ...), fill = NA, align = "left") %>% fn(., ...)
   #y <- outer(x, x, "-")
   #y[lower.tri(y)] %>% fn(., ...)  
  }

roll_maxChg <- function(x, fun, width,  ... ){
# For a given vector x, calculate the max/min change WITHIN each interval of the width "width" 
zoo::rollapply(x, width, maxChgWithin, fn = fun, ...,  fill = NA, align = "right")
  }

#  x <-   c(1,3,4,0,5, 2, -1,4,5,9)
#  x <- x[1:5]
#  x <- rnorm(1000)
#  system.time({roll_maxChg(x, max, 5, na.rm = T) %>% print})


system.time(
df_5yearMaxChg <- results_all %>% filter(runname %in% paste0("A1F075_", runs), year <= 30, sim >=1) %>% 
                  select(runname, year, sim, FR_MA, C_PR, ERC_PR, MA_PR) %>% 
                  group_by(sim, runname)  %>% 
                  mutate(
                    FR_MA = roll_maxChg(FR_MA, min, 5),
                    C_PR  = roll_maxChg(C_PR,  max, 5),
                    ERC_PR= roll_maxChg(ERC_PR,max, 5),
                    MA_PR = roll_maxChg(MA_PR, min, 5)) %>% 
                  summarise(FR_MA = min(FR_MA,  na.rm = TRUE),
                            C_PR  = max(C_PR,   na.rm = TRUE),
                            ERC_PR= max(ERC_PR, na.rm = TRUE),
                            MA_PR = min(MA_PR,  na.rm = TRUE)) %>% 
                group_by(runname) %>% 
                summarise_each(funs(median)) %>% select(-sim)
)
# Very slow. 

# Compare median 5-year change and median 5-year max change
df_5yearChg %>% filter(runname %in% paste0("A1F075_", runs))
df_5yearMaxChg
# The median 5-year max change is not necessarily greater than median 5-year change?



## Measures of volatility in M1 report table 3.(p25)

runs <- c(
 "0",
 "A5",
 "C15d",
 "C30d",
 "C30p",
 "O30p",
 "O30pA5"
)  


df_sd    %>% filter(runname %in% paste0("A1F075_", runs))
df_worst %>% filter(runname %in% paste0("A1F075_", runs))
df_final %>% filter(runname %in% paste0("A1F075_", runs))
df_5yearChg %>% filter(runname %in% paste0("A1F075_", runs))

df_5yearMaxChg

```


```{r single runs, include = FALSE, eval = FALSE}

# Picking single runs

expand_apply <- function(x, fun, ...){
   # Applying the given function to expanding windows of vector x.
   zoo::rollapply(x, seq_along(x), fun, ...,  fill = NA, align = "right")
  }

df_return <- 
results_all %>% filter(year <= 30, runname %in% "A1F075_0", sim > 0) %>% 
                select(runname, sim, year, i.r) %>% 
                group_by(sim) %>% 
                mutate(geoReturn.cum = expand_apply(i.r, get_geoReturn)) 

# See the distribution
df_return[df_return$year == 30, ]$geoReturn.cum %>% hist(breaks = seq(-0.3, 0.6, 0.01)) 
abline(v = 0.075)
df_return$geoReturn.cum %>% hist(breaks = seq(-0.5, 0.8, 0.01))
abline(v = 0.075)

df_return[df_return$year == 30, ]$geoReturn.cum %>% quantile(0.4)
# 0.06978279


# Look for sims with cumulative geo return close to 
  # seed(1234), nsim = 1000, mean 8.22%, sd 12%

# ending geo mean close to 7.5%
sim_select1 <- df_return %>% filter(year == 30, geoReturn.cum >=0.0746, geoReturn.cum <= 0.0754, sim >0) %>% 
               select(sim) %>% unlist %>% as.vector
sim_select1 
#  56   75  138  254  330  424  646  934 

# Ending geom mean close to 5.7%
sim_select2 <- df_return %>% filter(year == 30, geoReturn.cum >=0.0697, geoReturn.cum <= 0.0699, sim >0) %>% 
               select(sim) %>% unlist %>% as.vector
sim_select2
# 326  643  798  864   



# Choose candidates
df_return %>% filter(sim %in% sim_select1[1:4]) %>% qplot(year, geoReturn.cum, colour = factor(sim),  data =., geom = c("line", "point"))
df_return %>% filter(sim %in% sim_select1[5:8]) %>% qplot(year, geoReturn.cum, colour = factor(sim),  data =., geom = c("line", "point"))
# sims starting high: 56, 424, 646  
# sims starting low:  138, 254, 75

df_return %>% filter(sim %in% sim_select2) %>% qplot(year, geoReturn.cum, colour = factor(sim),  data =., geom = c("line", "point"))
# 326, 643, 798


# Graphs for Contributrion rate and funded status. 

gpanel.yy <- function(simnum, runs = runs_single){

# runs_single <- c("A1F075_C10d", "A1F075_O30pA5", "A1F075_soa1")
# simnum <-  646

df_single <- results_all %>%  filter(runname %in% runs_single, year <= 30) %>% 
                              filter(sim == simnum|(sim == 0 & runname == "A1F075_O30pA5")) %>% 
                              mutate(runname = ifelse(sim == 0, paste0(runname, "_Determ"), runname)) %>%  
                              group_by(runname, sim) %>% 
                              mutate(ir.gm   = expand_apply(i.r, get_geoReturn)) 


gmval <- df_single %>% filter(year == 30, sim == simnum, runname == runs_single[1]) %>% ungroup %>% select(ir.gm) %>% unlist
gmval <- 100*round(gmval, 3)

ls <- 1.25 # linesize
ps <- 2.25 # pointsize

 p1 <- ggplot(data=filter(df_single, sim == simnum, runname == runs_single[1]) %>% # any run will do
                  select(year, i.r, ir.gm) %>% 
                  gather(variable, value, -year, -runname, -sim),
                  aes(x = year, y = value*100, group = variable)) +
    geom_point(aes(colour=variable, shape=variable), size=ps) +
    geom_line(aes(colour=variable), size=ls) +
    scale_color_discrete(name = "") +
    scale_shape_discrete(name = "") +
    scale_linetype_discrete(name = "") +
    scale_y_continuous(breaks = c(seq(-50, 5, 5), 7.5, seq(10, 50, 5)), name = "Percent") + 
    scale_x_continuous(breaks = seq(0, 30, 5)) +
    geom_hline(yintercept = 7.5) +
    geom_hline(yintercept = 0, linetype="dotdash", size=.5) +
    labs(title=paste0("Annual returns and cumulative geometric mean: sim # ", simnum , "\n30-year geometric mean=", gmval )) +
    theme(plot.title=element_text(size=14))+
    theme_bw()

#p1

  p2 <- ggplot(data = df_single,
               aes(x = year, y = C_PR, group = runname)) +
    geom_point(aes(colour = runname, shape=runname), size = ps) +
    geom_line(aes(colour  = runname), size=ls) +
    scale_color_discrete(name = "") +
    scale_shape_discrete(name = "") +
    scale_linetype_discrete(name = "") +
    scale_y_continuous(breaks = seq(-10, 100, 5), name = "Percent") + 
    scale_x_continuous(breaks = seq(0, 30, 5)) +
    # geom_hline(y = ncpct$mdn) +
    labs(title=paste0("Contributions as % of payroll: sim # ", simnum)) +
    theme(plot.title=element_text(size=14)) + theme_bw()

#p2

  p3 <- ggplot(data= df_single, # use year 31 to get opening balance
               aes(x = year, y = FR_MA, group = runname)) +
    geom_point(aes(colour=runname, shape=runname), size=ps) +
    geom_line(aes(colour=runname), size=ls) +
    scale_color_discrete(name = "") +
    scale_shape_discrete(name = "") +
    scale_linetype_discrete(name = "") +
    scale_y_continuous(breaks=seq(30, 300, 10), name="Funded ratio at beginning of year") + 
    scale_x_continuous(breaks=seq(0, 30, 5)) +
    geom_hline(yintercept = 100) +
    labs(title=paste0("Funded ratio (based on MV assets): sim # ", simnum)) +
    theme(plot.title=element_text(size=14)) + theme_bw()

 # p3

  
   p4 <- ggplot(data= df_single, # use year 31 to get opening balance
               aes(x = year, y = MA_PR, group = runname)) +
    geom_point(aes(colour=runname, shape=runname), size=ps) +
    geom_line(aes(colour=runname), size=ls) +
    scale_color_discrete(name = "") +
    scale_shape_discrete(name = "") +
    scale_linetype_discrete(name = "") +
    scale_y_continuous(breaks=seq(0, 1000, 100), name="Asset to payroll ratio(%) ") + 
    scale_x_continuous(breaks=seq(0, 30, 5)) +
    labs(title=paste0("Asset to payroll ratio (based on MV assets): sim # ", simnum)) +
    theme(plot.title=element_text(size=14)) + theme_bw()

 #  p4

  # Add a table
  tbl <- df_single %>%
    group_by(runname, runname) %>%
    arrange(year) %>%
    mutate(Contrib.5yrchg=C_PR - lag(C_PR, 5),
           FR.5yrchg=FR_MA - lag(FR_MA, 5)) %>%
    summarise(Contrib.sd=round(sd(C_PR, na.rm=TRUE), 1),
              FR.sd=round(sd(FR_MA, na.rm=TRUE), 1),
              Contrib.max5yr_rise=round(max(Contrib.5yrchg, na.rm=TRUE), 1),
              FR.max5yr_fall=round(-min(FR.5yrchg, na.rm=TRUE), 1),
              Contrib.max5yr_rise=ifelse(Contrib.max5yr_rise>=0, Contrib.max5yr_rise, NA),
              FR.max5yr_fall=ifelse(FR.max5yr_fall>=0, FR.max5yr_fall, NA)) %>%
    mutate(Run = runname)  %>%
    ungroup %>%
    #arrange(runf2) %>%
    select(Run, Contrib.sd, FR.sd, Contrib.max5yr_rise, FR.max5yr_fall) %>%
    as.data.frame
  tbl
  colnames <- str_replace(names(tbl), "\\.", "\n")
  grob <- tableGrob(tbl, rows=NULL, cols=colnames)
   
  ml <- marrangeGrob(list(p1, p2, p3, p4, grob), 
                     layout_matrix = rbind(c(1,2),
                                           c(3,4),
                                           c(5,5)),
                     
                     nrow=3, ncol=2, top = NULL)
  # ml
  
  ggsave(paste0(IO_folder, "/Single_runs/g_", simnum, ".png"), ml, width=13, height=10, units="in")     

  invisible(ml)
}

runs_single <- c("A1F075_C10d", "A1F075_O30pA5", "A1F075_soa1")
panel1 <- apply(as.matrix(sim_select1), 1, gpanel.yy)
panel2 <- apply(as.matrix(sim_select2), 1, gpanel.yy)


```







