---
title: "Exploratory Analysis of Model Outputs"
author: "Yimeng Yin"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 4
---


```{r mainSet_options, echo=FALSE, cache=FALSE}

# options(width=140)
# knitr::opts_chunk$set(fig.width=16, fig.height=5, echo=FALSE)
# # Note: when saving maps (ggsave), width=16, height=9 seems to get rid of white space

```



```{r Preamble, echo = FALSE, include  = FALSE}
library(reshape2)
library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(knitr)
library(magrittr) # to use %<>%
library(zoo)
library(grid)
library(gridExtra)
library(stringr)

source("Functions.R")

rm(list = ls())

run_knitr <- F  #set to TRUE before knitting.
# When knitting HTML files, the working directory will be changed to the on where the .rmd file is located.
# The relative paths must be modified if they are not relative to the folder the .rmd file is located. 
# (When running the code line by line, it is covenient to set the paths relative to the folder of main model.)
  

if(run_knitr) source("../Functions.R") else source("Functions.R")
```


```{r Read, echo=FALSE, include = FALSE}
## Combine selected files into a single list.

IO_folder <- "IO_M2.1_new"

if(run_knitr) IO_folder <- paste0("../", IO_folder)

get_results <- function(IO_folder, Pattern = "^Outputs"){
  
  fn <- function(x) {
    load(paste0(IO_folder, "/", x))
    outputs_list$results}

  file_select <- dir(IO_folder, Pattern)
  results_all <- adply(file_select, 1, fn) %>% select(-X1)
}

results_all <- get_results(IO_folder, "^Outputs_I")
```




```{r, echo=FALSE, include = FALSE}

runs_all <- c(paste0("I7F075-", c(1)), paste0("I1F075-", c(6)), paste0("I6F075-", c(6)))

runs_all_labels <- c('runname, label.long, label.short 
I7F075-1,       The good old days,         The good old days
I1F075-6,       Invest in riskier assets,  Invest in riskier assets                       
I6F075-6,       Lower discount rate,       Lower discount rate'
)

runs_all_labels <- read.table(text = runs_all_labels, header = TRUE,sep = ",", stringsAsFactors = F) %>% 
                   mutate_each(funs(str_trim))

runs_all_labels



df_plot1 <- results_all  %>% 
  filter(runname %in% runs_all, sim > 0, year <= 30 )

df_dc75 <- df_plot1 %>% filter(runname == runs_all[1]) %>% select(sim, year, AL75 = AL)

df_plot1 <- df_plot1 %>% 
  left_join(df_dc75) %>% 
  select(runname, sim, year, AL75, MA, ERC_PR) %>% 
  group_by(runname, sim) %>% 
  mutate(FR_MA     = 100 * MA / AL75,
         FR40less  = cumany(FR_MA <= 40),
         ERC_high  = cumany(ERC_PR >= 30), 
         ERC_hike  = cumany(na2zero(ERC_PR - lag(ERC_PR, 5) >= 10))) %>% 
  group_by(runname, year) %>% 
  summarize(FR40less = 100 * sum(FR40less, na.rm = T)/n(),
            ERC_high = 100 * sum(ERC_high, na.rm = T)/n(),
            ERC_hike = 100 * sum(ERC_hike, na.rm = T)/n(),
            FR.med   = median(FR_MA),
            ERC_PR.med= median(ERC_PR)
            ) %>% 
  left_join(runs_all_labels) %>% ungroup() %>% 
  mutate(runname = factor(runname, levels = runs_all, 
                          labels = c("The good old days", 
                                     "Invest in riskier assets",
                                     "Lower discount rate")))




p.FR.med <- 
ggplot(df_plot1, aes(x = year, y = FR.med, color = runname, shape = runname, label = label.short)) + theme_bw() + 
  geom_point(size = 3) + geom_line() +
  geom_hline(yintercept = 100, linetype = 2, color = "black") + 
  coord_cartesian(ylim = c(0, 150)) + 
  scale_x_continuous(breaks = seq(0,30, 5))+ 
  scale_y_continuous(breaks = seq(0,200, 25)) + 
  labs(x = "Year",
       y = "Funded ratio (%)",
       title = "Median funded ratio") + 
  guides(col = guide_legend(title = NULL), shape = guide_legend(title = NULL)) + 
  theme(legend.justification=c(0,1), legend.position=c(0,1),
        legend.background = element_rect(color = "grey",  size=0.5, linetype=1))
p.FR.med


p.FR40less <- 
ggplot(df_plot1, aes(x = year, y = FR40less, color = runname, shape = runname, label = label.short)) + theme_bw() + 
  geom_point(size = 3) + geom_line() +
  coord_cartesian(ylim = c(0, 20)) + 
  scale_x_continuous(breaks = seq(0,30, 5))+ 
  scale_y_continuous(breaks = seq(0,20, 5)) + 
  labs(x = "Year",
       y = "Probability (%)",
       title = "Probability of funded ratio falling below 40% \nat any time prior to and including the given year") + 
  guides(col = guide_legend(title = NULL), shape = guide_legend(title = NULL)) + 
  theme(legend.justification=c(0,1), legend.position=c(0,1),
        legend.background = element_rect(color = "grey",  size=0.5, linetype=1))
p.FR40less




p.ERC_PR.med <- 
ggplot(df_plot1, aes(x = year, y = ERC_PR.med, color = runname, shape = runname, label = label.short)) + theme_bw() + 
  geom_point(size = 3) + geom_line() +
  coord_cartesian(ylim = c(0, 50)) + 
  scale_x_continuous(breaks = seq(0,30, 5))+ 
  scale_y_continuous(breaks = seq(0,60, 5)) + 
  labs(x = "Year",
       y = "Employer contribution rate (%)",
       title = "Median employer contribution as a percentage of payroll") + 
  guides(col = guide_legend(title = NULL), shape = guide_legend(title = NULL)) + 
  theme(legend.justification=c(1,1), legend.position=c(1,1),
        legend.background = element_rect(color = "grey",  size=0.5, linetype=1))
p.ERC_PR.med



p.ERC_high <- 
ggplot(df_plot1, aes(x = year, y = ERC_high, color = runname, shape = runname, label = label.short)) + theme_bw() + 
  geom_point(size = 3) + geom_line() +
  coord_cartesian(ylim = c(0, 100)) + 
  scale_x_continuous(breaks = seq(0,30, 5))+ 
  scale_y_continuous(breaks = seq(0,100, 10)) + 
  labs(x = "Year",
       y = "Probability (%)",
       title = "Probability of Employer contribution above 30% of payroll \nat any time prior to and including the given year ") + 
  guides(col = guide_legend(title = NULL), shape = guide_legend(title = NULL)) + 
  theme(legend.justification=c(0,1), legend.position=c(0,0.9),
        legend.background = element_rect(color = "grey",  size=0.5, linetype=1))
p.ERC_high


p.ERC_hike <- 
ggplot(df_plot1, aes(x = year, y = ERC_hike, color = runname, shape = runname, label = label.short)) + theme_bw() + 
  geom_point(size = 3) + geom_line() +
  coord_cartesian(ylim = c(0, 20)) + 
  scale_x_continuous(breaks = seq(0,30, 5))+ 
  scale_y_continuous(breaks = seq(0,100, 10)) + 
  labs(x = "Year",
       y = "Probability (%)",
       title = "Probability of employer contribution rising by more than \n10% of payroll at any time prior to and including the given year ") + 
  guides(col = guide_legend(title = NULL), shape = guide_legend(title = NULL)) + 
  theme(legend.justification=c(0,1), legend.position=c(0,1),
        legend.background = element_rect(color = "grey",  size=0.5, linetype=1))
p.ERC_hike


g.width = 6
g.height = 5.5
g.folder = "/Slides_CAtrip_May2016/"

ggsave(paste0(IO_folder, g.folder, "p.FR.med.png"), p.FR.med, width=g.width, height=g.height, units="in")
ggsave(paste0(IO_folder, g.folder, "p.FR40less.png"), p.FR40less, width=g.width, height=g.height, units="in")
ggsave(paste0(IO_folder, g.folder, "p.ERC_PR.med.png"), p.ERC_PR.med, width=g.width, height=g.height, units="in")
ggsave(paste0(IO_folder, g.folder, "p.ERC_high.png"), p.ERC_high, width=g.width, height=g.height, units="in")
ggsave(paste0(IO_folder, g.folder, "p.ERC_hike.png"), p.ERC_hike, width=g.width, height=g.height, units="in")


```





```{r, echo=FALSE, include = FALSE}


runs_all2 <- paste0("I8F075-", 2:4)

# runs_all_labels <- c('runname, label.long, label.short 
# I8F075-1,       The good old days,         The good old days
# I8F075-6,       Invest in riskier assets,  Invest in riskier assets                       
# I8F075-6,       Lower discount rate,       Lower discount rate'
# )
# 
# runs_all_labels <- read.table(text = runs_all_labels, header = TRUE,sep = ",", stringsAsFactors = F) %>% 
#                    mutate_each(funs(str_trim))

# runs_all_labels 



df_plot2 <- results_all  %>% 
  filter(runname %in% runs_all2, sim > 0, year <= 30 )

df_dc75 <- df_plot2 %>% filter(runname == runs_all2[1]) %>% select(sim, year, AL75 = AL)

df_plot2 <- df_plot2 %>% 
  left_join(df_dc75) %>% 
  select(runname, sim, year, AL75, MA, ERC_PR) %>% 
  group_by(runname, sim) %>% 
  mutate(FR_MA     = 100 * MA / AL75,
         FR40less  = cumany(FR_MA <= 40),
         ERC_high  = cumany(ERC_PR >= 30), 
         ERC_hike  = cumany(na2zero(ERC_PR - lag(ERC_PR, 5) >= 10))) %>% 
  group_by(runname, year) %>% 
  summarize(FR40less = 100 * sum(FR40less, na.rm = T)/n(),
            ERC_high = 100 * sum(ERC_high, na.rm = T)/n(),
            ERC_hike = 100 * sum(ERC_hike, na.rm = T)/n(),
            FR.med   = median(FR_MA),
            ERC_PR.med= median(ERC_PR)
            ) %>% 
  #left_join(runs_all_labels) %>% 
  ungroup() %>% 
  mutate(runname = factor(runname, levels = runs_all2, 
                          labels = c("Standard deviation = 8%", 
                                     "Standard deviation = 12%",
                                     "Standard deviation = 16%")))




p.FR.med <- 
ggplot(df_plot2, aes(x = year, y = FR.med, color = runname, shape = runname)) + theme_bw() + 
  geom_point(size = 3) + geom_line() +
  geom_hline(yintercept = 100, linetype = 2, color = "black") + 
  coord_cartesian(ylim = c(0, 150)) + 
  scale_x_continuous(breaks = seq(0,30, 5))+ 
  scale_y_continuous(breaks = seq(0,200, 25)) + 
  labs(x = "Year",
       y = "Funded ratio (%)",
       title = "Median funded ratio") + 
  guides(col = guide_legend(title = NULL), shape = guide_legend(title = NULL)) + 
  theme(legend.justification=c(0,1), legend.position=c(0,1),
        legend.background = element_rect(color = "grey",  size=0.5, linetype=1))
p.FR.med


p.FR40less <- 
ggplot(df_plot2, aes(x = year, y = FR40less, color = runname, shape = runname)) + theme_bw() + 
  geom_point(size = 3) + geom_line() +
  coord_cartesian(ylim = c(0, 35)) + 
  scale_x_continuous(breaks = seq(0,30, 5))+ 
  scale_y_continuous(breaks = seq(0,50, 5)) + 
  labs(x = "Year",
       y = "Probability (%)",
       title = "Probability of funded ratio falling below 40% \nat any time prior to and including the given year") + 
  guides(col = guide_legend(title = NULL), shape = guide_legend(title = NULL)) + 
  theme(legend.justification=c(0,1), legend.position=c(0,1),
        legend.background = element_rect(color = "grey",  size=0.5, linetype=1))
p.FR40less




p.ERC_PR.med <- 
ggplot(df_plot2, aes(x = year, y = ERC_PR.med, color = runname, shape = runname)) + theme_bw() + 
  geom_point(size = 3) + geom_line() +
  coord_cartesian(ylim = c(0, 50)) + 
  scale_x_continuous(breaks = seq(0,30, 5))+ 
  scale_y_continuous(breaks = seq(0,60, 5)) + 
  labs(x = "Year",
       y = "Employer contribution rate (%)",
       title = "Median employer contribution as a percentage of payroll") + 
  guides(col = guide_legend(title = NULL), shape = guide_legend(title = NULL)) + 
  theme(legend.justification=c(1,1), legend.position=c(1,1),
        legend.background = element_rect(color = "grey",  size=0.5, linetype=1))
p.ERC_PR.med



p.ERC_high <- 
ggplot(df_plot2, aes(x = year, y = ERC_high, color = runname, shape = runname)) + theme_bw() + 
  geom_point(size = 3) + geom_line() +
  coord_cartesian(ylim = c(0, 15)) + 
  scale_x_continuous(breaks = seq(0,30, 5))+ 
  scale_y_continuous(breaks = seq(0,100, 10)) + 
  labs(x = "Year",
       y = "Probability (%)",
       title = "Probability of Employer contribution above 30% of payroll \nat any time prior to and including the given year ") + 
  guides(col = guide_legend(title = NULL), shape = guide_legend(title = NULL)) + 
  theme(legend.justification=c(0,1), legend.position=c(0,0.9),
        legend.background = element_rect(color = "grey",  size=0.5, linetype=1))
p.ERC_high


p.ERC_hike <- 
ggplot(df_plot2, aes(x = year, y = ERC_hike, color = runname, shape = runname)) + theme_bw() + 
  geom_point(size = 3) + geom_line() +
  coord_cartesian(ylim = c(0, 40)) + 
  scale_x_continuous(breaks = seq(0,30, 5))+ 
  scale_y_continuous(breaks = seq(0,100, 5)) + 
  labs(x = "Year",
       y = "Probability (%)",
       title = "Probability of employer contribution rising by more than \n10% of payroll at any time prior to and including the given year ") + 
  guides(col = guide_legend(title = NULL), shape = guide_legend(title = NULL)) + 
  theme(legend.justification=c(0,1), legend.position=c(0,1),
        legend.background = element_rect(color = "grey",  size=0.5, linetype=1))
p.ERC_hike


g.width = 6
g.height = 5.5
g.folder = "/Slides_CAtrip_May2016/"

ggsave(paste0(IO_folder, g.folder, "p2.FR.med.png"), p.FR.med, width=g.width, height=g.height, units="in")
ggsave(paste0(IO_folder, g.folder, "p2.FR40less.png"), p.FR40less, width=g.width, height=g.height, units="in")
ggsave(paste0(IO_folder, g.folder, "p2.ERC_PR.med.png"), p.ERC_PR.med, width=g.width, height=g.height, units="in")
ggsave(paste0(IO_folder, g.folder, "p2.ERC_high.png"), p.ERC_high, width=g.width, height=g.height, units="in")
ggsave(paste0(IO_folder, g.folder, "p2.ERC_hike.png"), p.ERC_hike, width=g.width, height=g.height, units="in")


```







```{r, echo=FALSE, include = FALSE}

# Demographics

results_demo <- get_results(IO_folder, "^Outputs_D")

runs_all3 <- c("D1F075-average_gn2",
               "D1F075-average",
               "D1F075-average_g2", 
               "D1F075-mature1_gn1")


# runs_all_labels <- c('runname, label.long, label.short 
# I8F075-1,       The good old days,         The good old days
# I8F075-6,       Invest in riskier assets,  Invest in riskier assets                       
# I8F075-6,       Lower discount rate,       Lower discount rate'
# )
# 
# runs_all_labels <- read.table(text = runs_all_labels, header = TRUE,sep = ",", stringsAsFactors = F) %>% 
#                    mutate_each(funs(str_trim))

# runs_all_labels 



df_plot3 <- results_demo  %>% 
  filter(runname %in% runs_all3, sim > 0, year <= 30 )


df_plot3 <- df_plot3 %>% 
  left_join(df_dc75) %>% 
  select(runname, sim, year, AL, MA, ERC_PR) %>% 
  group_by(runname, sim) %>% 
  mutate(FR_MA     = 100 * MA / AL,
         FR40less  = cumany(FR_MA <= 40),
         ERC_high  = cumany(ERC_PR >= 30), 
         ERC_hike  = cumany(na2zero(ERC_PR - lag(ERC_PR, 5) >= 10))) %>% 
  group_by(runname, year) %>% 
  summarize(FR40less = 100 * sum(FR40less, na.rm = T)/n(),
            ERC_high = 100 * sum(ERC_high, na.rm = T)/n(),
            ERC_hike = 100 * sum(ERC_hike, na.rm = T)/n(),
            FR.med   = median(FR_MA),
            ERC_PR.med= median(ERC_PR)
            ) %>% 
  #left_join(runs_all_labels) %>% 
  ungroup() %>% 
  mutate(runname = factor(runname, levels = runs_all3, 
                          labels = c("Average, 2% decline", 
                                     "Average, constant workforce",
                                     "Average, 2% growth",
                                     "Mature plan (high asset-payroll ratio)")))




pd.FR.med <- 
ggplot(df_plot3, aes(x = year, y = FR.med, color = runname, shape = runname)) + theme_bw() + 
  geom_point(size = 3) + geom_line() +
  geom_hline(yintercept = 100, linetype = 2, color = "black") + 
  coord_cartesian(ylim = c(0, 150)) + 
  scale_x_continuous(breaks = seq(0,30, 5))+ 
  scale_y_continuous(breaks = seq(0,200, 25)) + 
  labs(x = "Year",
       y = "Funded ratio (%)",
       title = "Median funded ratio") + 
  guides(col = guide_legend(title = NULL), shape = guide_legend(title = NULL)) + 
  theme(legend.justification=c(0,1), legend.position=c(0,1),
        legend.background = element_rect(color = "grey",  size=0.5, linetype=1))
pd.FR.med


pd.FR40less <- 
ggplot(df_plot3, aes(x = year, y = FR40less, color = runname, shape = runname)) + theme_bw() + 
  geom_point(size = 3) + geom_line() +
  coord_cartesian(ylim = c(0, 100)) + 
  scale_x_continuous(breaks = seq(0,30, 5))+ 
  scale_y_continuous(breaks = seq(0,100, 10)) + 
  labs(x = "Year",
       y = "Probability (%)",
       title = "Probability of funded ratio falling below 40% \nat any time prior to and including the given year") + 
  guides(col = guide_legend(title = NULL), shape = guide_legend(title = NULL)) + 
  theme(legend.justification=c(0,1), legend.position=c(0,1),
        legend.background = element_rect(color = "grey",  size=0.5, linetype=1))
pd.FR40less




pd.ERC_PR.med <- 
ggplot(df_plot3, aes(x = year, y = ERC_PR.med, color = runname, shape = runname)) + theme_bw() + 
  geom_point(size = 3) + geom_line() +
  coord_cartesian(ylim = c(0, 50)) + 
  scale_x_continuous(breaks = seq(0,30, 5))+ 
  scale_y_continuous(breaks = seq(0,60, 5)) + 
  labs(x = "Year",
       y = "Employer contribution rate (%)",
       title = "Median employer contribution as a percentage of payroll") + 
  guides(col = guide_legend(title = NULL), shape = guide_legend(title = NULL)) + 
  theme(legend.justification=c(1,1), legend.position=c(1,1),
        legend.background = element_rect(color = "grey",  size=0.5, linetype=1))
pd.ERC_PR.med



pd.ERC_high <- 
ggplot(df_plot3, aes(x = year, y = ERC_high, color = runname, shape = runname)) + theme_bw() + 
  geom_point(size = 3) + geom_line() +
  coord_cartesian(ylim = c(0, 100)) + 
  scale_x_continuous(breaks = seq(0,30, 5))+ 
  scale_y_continuous(breaks = seq(0,100, 10)) + 
  labs(x = "Year",
       y = "Probability (%)",
       title = "Probability of Employer contribution above 30% of payroll \nat any time prior to and including the given year ") + 
  guides(col = guide_legend(title = NULL), shape = guide_legend(title = NULL)) + 
  theme(legend.justification=c(0,1), legend.position=c(0,1),
        legend.background = element_rect(color = "grey",  size=0.5, linetype=1))
pd.ERC_high


pd.ERC_hike <- 
ggplot(df_plot3, aes(x = year, y = ERC_hike, color = runname, shape = runname)) + theme_bw() + 
  geom_point(size = 3) + geom_line() +
  coord_cartesian(ylim = c(0, 100)) + 
  scale_x_continuous(breaks = seq(0,30, 5))+ 
  scale_y_continuous(breaks = seq(0,100, 10)) + 
  labs(x = "Year",
       y = "Probability (%)",
       title = "Probability of employer contribution rising by more than \n10% of payroll at any time prior to and including the given year ") + 
  guides(col = guide_legend(title = NULL), shape = guide_legend(title = NULL)) + 
  theme(legend.justification=c(0,1), legend.position=c(0,1),
        legend.background = element_rect(color = "grey",  size=0.5, linetype=1))
pd.ERC_hike


g.width = 6
g.height = 5.5
g.folder = "/Slides_CAtrip_May2016/"

ggsave(paste0(IO_folder, g.folder, "pd.FR.med.png"), pd.FR.med, width=g.width, height=g.height, units="in")
ggsave(paste0(IO_folder, g.folder, "pd.FR40less.png"), pd.FR40less, width=g.width, height=g.height, units="in")
ggsave(paste0(IO_folder, g.folder, "pd.ERC_PR.med.png"), pd.ERC_PR.med, width=g.width, height=g.height, units="in")
ggsave(paste0(IO_folder, g.folder, "pd.ERC_high.png"), pd.ERC_high, width=g.width, height=g.height, units="in")
ggsave(paste0(IO_folder, g.folder, "pd.ERC_hike.png"), pd.ERC_hike, width=g.width, height=g.height, units="in")


```












