---
title: "Exploratory Analysis of Model Outputs"
author: "Yimeng Yin"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 4
---


```{r mainSet options, echo=FALSE, cache=FALSE}

# options(width=140)
# knitr::opts_chunk$set(fig.width=16, fig.height=5, echo=FALSE)
# # Note: when saving maps (ggsave), width=16, height=9 seems to get rid of white space

```




```{r Preamble, echo = FALSE, include  = FALSE}
library(reshape2)
library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(knitr)
library(magrittr) # to use %<>%
library(zoo)
library(grid)

rm(list = ls())

run_knitr <- T

if(run_knitr) source("../Functions.R") else source("Functions.R")

```


```{r, echo=FALSE, include = FALSE}
## Combine selected files into a single list.

if(run_knitr) folder_run <- "../IO_M2.1" else folder_run <- "IO_M2.1"

file_select <- dir(folder_run, pattern = ".RData")

fn <- function(x) {
       load(paste0(folder_run, "/", x))
       outputs_list
  }

lists_all        <- alply(file_select, 1, fn)
names(lists_all) <- laply(lists_all, function(x) x$paramlist$runname)

## Combine the results into a single data frame.
results_all <- ldply(lists_all, function(x) x$results) %>% select(-X1)

rm(lists_all)
```


```{r Read, echo=FALSE, include = FALSE}

results_all %<>% mutate(dFR = FR - lag(FR),
                        dFR_MA = FR_MA - lag(FR_MA),
                        dC_PR = C_PR - lag(C_PR))


```


## Demographics, 100% Initial Funding, no workforce growth

Columns:
1.	Average
2.	Young Plan
3.	Old Plan
4.	High abratio
5.	Underfunded Teachers

```{r, echo = FALSE, cache = F , eval = TRUE, fig.width=20, fig.height=4}

prefix <- "DF100-"

DF100_FR     <- draw_quantiles(paste0(prefix, c(1:6) ), "FR",    ylim = c(0, 250))    
DF100_C_PR   <- draw_quantiles(paste0(prefix, c(1:6)), "C_PR",   ylim = c(-2, 35))
DF100_ERC_PR <- draw_quantiles(paste0(prefix, c(1:6)), "ERC_PR", ylim = c(-2, 35))

DF100_FR$plot
DF100_C_PR$plot
# DF100_ERC_PR$plot

# DF100_FR$df %>% glimpse()
# DF100_C_PR$df
# DF100_ERC_PR$plot

```

## Demographics,  100% Initial Funding, 2% workforce growth


Columns:
1.	Average
2.	Young Plan
3.	Old Plan
4.	High abratio
5.	Underfunded Teachers


```{r, echo = FALSE, cache = F , eval = TRUE, fig.width=20, fig.height=4}

prefix <- "DF100-"

DF100g_FR     <- draw_quantiles(paste0(prefix, c(1:6), "g" ), "FR",    ylim = c(0, 250))    
DF100g_C_PR   <- draw_quantiles(paste0(prefix, c(1:6), "g"), "C_PR",   ylim = c(-2, 35))
DF100g_ERC_PR <- draw_quantiles(paste0(prefix, c(1:6), "g"), "ERC_PR", ylim = c(-2, 35))

DF100g_FR$plot
DF100g_C_PR$plot
# DF100g_ERC_PR$plot

# DF100g_FR$df %>% glimpse()
# DF100g_C_PR$df
# DF100g_ERC_PR$plot

```



## Benefit Policy, 100% Initial Funding, COLA

```{r, echo = FALSE, cache = F , eval = TRUE, fig.width=14, fig.height=6}

prefix <- "BF100-"

BF100_FR     <- draw_quantiles(paste0(prefix, c(1:2)), "FR",    ylim = c(0, 250), year.max = 80)    
BF100_C_PR   <- draw_quantiles(paste0(prefix, c(1:2)), "C_PR",   ylim = c(-2, 35), year.max = 80)
BF100_ERC_PR <- draw_quantiles(paste0(prefix, c(1:2)), "ERC_PR", ylim = c(-2, 35))

BF100_FR$plot
BF100_C_PR$plot
# BF100_ERC_PR$plot

# BF100_FR$df %>% glimpse()
# BF100_C_PR$df
# BF100_ERC_PR$plot

```



















